- alias: aparinki
  city: Апаринки
  inCity: в Апаринках
  coordinates:
    - 55.572029
    - 37.760557
  address: ''
  phone: 84954093741
  yandex: 94bc7c3ca7b6e2dc
- alias: arhangelskoe
  city: Архангельское
  inCity: в Архангельском
  coordinates:
    - 55.789406
    - 37.301204
  address: ''
  phone: 84954093741
  yandex: 77f5407e36dc2699
- alias: balashiha
  city: Балашиха
  inCity: в Балашихе
  coordinates:
    - 55.796339
    - 37.938199
  address: ''
  phone: 84954093741
  yandex: d0ce310cd887e38f
- alias: barviha
  city: Барвиха
  inCity: в Барвихе
  coordinates:
    - 55.724165
    - 37.280884
  address: ''
  phone: 84954093741
  yandex: 3855baf2a49e4205
- alias: butovo
  city: Бутово
  inCity: в Бутово
  coordinates:
    - 55.545044
    - 37.589976
  address: ''
  phone: 84954093741
  yandex: 1db01d8fee1a247a
- alias: vidnoe
  city: Видное
  inCity: в Видном
  coordinates:
    - 55.557174
    - 37.708644
  address: ''
  phone: 84954093741
  yandex: f8274b102e2d7c34
- alias: vlasiha
  city: Власиха
  inCity: во Власихе
  coordinates:
    - 55.685503
    - 37.190423
  address: ''
  phone: 84954093741
  yandex: 63557712985a0c10
- alias: voskresenskoe
  city: Воскресенское
  inCity: в Воскресенском
  coordinates:
    - 55.517495
    - 37.442572
  address: ''
  phone: 84954093741
  yandex: d936dd177a893ce6
- alias: veshki
  city: Вёшки
  inCity: в Вёшках
  coordinates:
    - 55.926408
    - 37.605876
  address: ''
  phone: 84954093741
  yandex: 0eb127a91e39b2c6
- alias: dedovsk
  city: Дедовск
  inCity: в Дедовске
  coordinates:
    - 55.859984
    - 37.120669
  address: ''
  phone: 84954093741
  yandex: 94aeb6da31677c80
- alias: dzerzhinskii
  city: Дзержинский
  inCity: в Дзержинском
  coordinates:
    - 55.63096
    - 37.849679
  address: ''
  phone: 84954093741
  yandex: 1268fae8f8a876b0
- alias: dolgoprudnyi
  city: Долгопрудный
  inCity: в Долгопрудном
  coordinates:
    - 55.93362
    - 37.514401
  address: ''
  phone: 84954093741
  yandex: b215cb0d7fa2cb8a
- alias: domodedovo
  city: Домодево
  inCity: в Домодедово
  coordinates:
    - 55.437112
    - 37.768049
  address: ''
  phone: 84954093741
  yandex: 9d6c05103a6eb952
- alias: zheleznodorozhnyi
  city: Железнодорожный
  inCity: в Железнодорожном
  coordinates:
    - 55.746436
    - 38.009049
  address: ''
  phone: 84954093741
  yandex: 79fee4fe1995073d
- alias: zhukovskii
  city: Жуковский
  inCity: в Жуковском
  coordinates:
    - 55.59778
    - 38.119497
  address: ''
  phone: 84954093741
  yandex: 8becc8ae3ec6f4c5
- alias: zelenograd
  city: Зеленоград
  inCity: в Зеленограде
  coordinates:
    - 55.991893
    - 37.214382
  address: ''
  phone: 84954093741
  yandex: 25badd0012883cae
- alias: ivanteevka
  city: Ивантеевка
  inCity: в Ивантеевке
  coordinates:
    - 55.97
    - 37.917574
  address: ''
  phone: 84954093741
  yandex: dc2ae4d2b3cdafdf
- alias: ilinskoe
  city: Ильинское-Усово
  inCity: в Ильинское-Усово
  coordinates:
    - 55.766136
    - 37.220265
  address: ''
  phone: 84954093741
  yandex: 5cd156b9ffe3ec64
- alias: istra
  city: Истра
  inCity: в Истре
  coordinates:
    - 55.914287
    - 36.860284
  address: ''
  phone: 84954093741
  yandex: a254f0fff61dc41a
- alias: cliazma
  city: Клязьма
  inCity: в Клязьме
  coordinates:
    - 55.978161
    - 37.833842
  address: ''
  phone: 84954093741
  yandex: afa6add859d548e1
- alias: korolev
  city: Королев
  inCity: в Королеве
  coordinates:
    - 55.922212
    - 37.854629
  address: ''
  phone: 84954093741
  yandex: 3fedfea67e4288ca
- alias: kotelniki
  city: Котельники
  inCity: в Котельниках
  coordinates:
    - 55.65984
    - 37.863199
  address: ''
  phone: 84954093741
  yandex: ef8bd46bc5d60c04
- alias: kraskovo
  city: Красково
  inCity: в Красково
  coordinates:
    - 55.658886
    - 37.98846
  address: ''
  phone: 84954093741
  yandex: 8a10270707cdfba6
- alias: krasnogorsk
  city: Красногорск
  inCity: в Красногорске
  coordinates:
    - 55.831099
    - 37.330192
  address: ''
  phone: 84954093741
  yandex: 8c5cc48cb1a897f6
- alias: kurkino
  city: Куркино
  inCity: в Куркино
  coordinates:
    - 55.891239
    - 37.389661
  address: ''
  phone: 84954093741
  yandex: 7e5c16031370918a
- alias: lobnia
  city: Лобня
  inCity: в Лобне
  coordinates:
    - 56.012053
    - 37.475082
  address: ''
  phone: 84954093741
  yandex: 7ed18d8cf571b331
- alias: lytkarino
  city: Лыткарино
  inCity: в Лыткарино
  coordinates:
    - 55.577856
    - 37.90347
  address: ''
  phone: 84954093741
  yandex: c73b7631a14e192c
- alias: lyubertcy
  city: Люберцы
  inCity: в Люберцах
  coordinates:
    - 55.676494
    - 37.898116
  address: ''
  phone: 84954093741
  yandex: b5a9f2fa4fe1ec1e
- alias: malahovka
  city: Малаховка
  inCity: в Малаховке
  coordinates:
    - 55.64258
    - 38.009373
  address: ''
  phone: 84954093741
  yandex: 0a8d939850b04ce2
- alias: mechnikovo
  city: Мечниково
  inCity: в Мечниково
  coordinates:
    - 55.749831
    - 37.162252
  address: ''
  phone: 84954093741
  yandex: 05e9e89c5b940154
- alias: moscow
  city: Москва
  inCity: в Москве
  coordinates:
    - 55.755814
    - 37.617635
  address: ''
  phone: 84954093741
  yandex: 2882d8a93f35322b
- alias: moskovskii
  city: Московский
  inCity: в Московском
  coordinates:
    - 55.602144
    - 37.346551
  address: ''
  phone: 84954093741
  yandex: 94b70e3f40bd1d91
- alias: mytishchi
  city: Мытищи
  inCity: в Мытищах
  coordinates:
    - 55.910503
    - 37.73633
  address: ''
  phone: 84954093741
  yandex: 14c3722a9abe9fd5
- alias: nahabino
  city: Нахабино
  inCity: в Нахабино
  coordinates:
    - 55.847149
    - 37.180138
  address: ''
  phone: 84954093741
  yandex: da1b7e04f8ae4955
- alias: novogorsk
  city: Новогорск
  inCity: в Новогорске
  coordinates:
    - 55.892178
    - 37.350279
  address: ''
  phone: 84954093741
  yandex: 49619a45dd2597f8
- alias: odintcovo
  city: Одинцово
  inCity: в Одинцово
  coordinates:
    - 55.678895
    - 37.26387
  address: ''
  phone: 84954093741
  yandex: 7e30f3c57b5e4385
- alias: opaliha
  city: Опалиха
  inCity: в Опалихе
  coordinates:
    - 55.827732
    - 37.252731
  address: ''
  phone: 84954093741
  yandex: 2f4973a377beb836
- alias: petrovo-dalnee
  city: Петрово-Дальнее
  inCity: в Петрово-Дальнее
  coordinates:
    - 55.751366
    - 37.178691
  address: ''
  phone: 84954093741
  yandex: 9feace978aa44106
- alias: pirogovo
  city: Пирогово
  inCity: в Пирогово
  coordinates:
    - 55.97872
    - 37.729727
  address: ''
  phone: 84954093741
  yandex: c5744df0ccd47aef
- alias: podolsk
  city: Подольск
  inCity: в Подольске
  coordinates:
    - 55.431177
    - 37.544737
  address: ''
  phone: 84954093741
  yandex: 3a81c0bc0bc88339
- alias: putilkovo
  city: Путилково
  inCity: в Путилково
  coordinates:
    - 55.863636
    - 37.392113
  address: ''
  phone: 84954093741
  yandex: c389d10ce50ccb85
- alias: pushkino
  city: Пушкино
  inCity: в Пушкине
  coordinates:
    - 56.010428
    - 37.847155
  address: ''
  phone: 84954093741
  yandex: 12877f19048be05a
- alias: rastorguevo
  city: Расторгуево
  inCity: в Расторгуево
  coordinates:
    - 55.544509
    - 37.672136
  address: ''
  phone: 84954093741
  yandex: 17e9bb6208af8824
- alias: reutov
  city: Реутов
  inCity: в Реутове
  coordinates:
    - 55.760515
    - 37.855141
  address: ''
  phone: 84954093741
  yandex: 1ac525cf216ea481
- alias: rublevo
  city: Рублево
  inCity: в Рублево
  coordinates:
    - 55.786288
    - 37.35539
  address: ''
  phone: 84954093741
  yandex: 5ac9fe07c7ad2fb1
- alias: saltykovka
  city: Салтыковка
  inCity: в Салтыковке
  coordinates:
    - 55.762713
    - 37.922461
  address: ''
  phone: 84954093741
  yandex: c027362d0e481fa9
- alias: shodnya
  city: Сходня
  inCity: в Сходне
  coordinates:
    - 55.951572
    - 37.295607
  address: ''
  phone: 84954093741
  yandex: ef8f844f56c5cb83
- alias: tomilino
  city: Томилино
  inCity: в Томилино
  coordinates:
    - 55.663126
    - 37.949931
  address: ''
  phone: 84954093741
  yandex: ae657c223c8012cf
- alias: troitck
  city: Троицк
  inCity: в Троицке
  coordinates:
    - 55.485469
    - 37.305327
  address: ''
  phone: 84954093741
  yandex: ffe5becdfb7e1366
- alias: himki
  city: Химки
  inCity: в Химках
  coordinates:
    - 55.888796
    - 37.430328
  address: ''
  phone: 84954093741
  yandex: 8cbe21192e0cf796
- alias: shchelkovo
  city: Щелково
  inCity: в Щелково
  coordinates:
    - 55.923387
    - 37.978399
  address: ''
  phone: 84954093741
  yandex: 86b36d35b4d7ca20
- alias: shcherbinka
  city: Щербинка
  inCity: в Щербинке
  coordinates:
    - 55.508743
    - 37.563314
  address: ''
  phone: 84954093741
  yandex: 3fb91ed8cae84553
