- alias: aparinki
  city: Апаринки
  inCity: в Апаринках
  coordinates:
    - 55.570008
    - 37.75956
  address: владение 5
  fullAddress: 'деревня Апаринки, вл5'
  phone: 84954093741
  yandex: 94bc7c3ca7b6e2dc
- alias: arhangelskoe
  city: Архангельское
  inCity: в Архангельском
  coordinates:
    - 55.789031
    - 37.2962
  address: 24А
  fullAddress: 'городской округ Красногорск, посёлок Архангельское, 24А'
  phone: 84954093741
  yandex: 77f5407e36dc2699
- alias: balashiha
  city: Балашиха
  inCity: в Балашихе
  coordinates:
    - 55.808705
    - 37.95736
  address: 'улица Текстильщиков, 16'
  fullAddress: 'Балашиха, улица Текстильщиков, 16'
  phone: 84954093741
  yandex: d0ce310cd887e38f
- alias: barviha
  city: Барвиха
  inCity: в Барвихе
  coordinates:
    - 55.724165
    - 37.280884
  address: ''
  fullAddress: 'Одинцовский район, сельское поселение Барвихинское'
  phone: 84954093741
  yandex: 3855baf2a49e4205
- alias: butovo
  city: Бутово
  inCity: в Бутово
  coordinates:
    - 55.530872
    - 37.57104
  address: 'Проектируемый проезд 185,владение 8с5'
  fullAddress: 'Москва, Проектируемый проезд № 185, вл8с5'
  phone: 84954093741
  yandex: 1db01d8fee1a247a
- alias: vidnoe
  city: Видное
  inCity: в Видном
  coordinates:
    - 55.549959
    - 37.721211
  address: 'проспект Ленинского Комсомола, 1Д'
  fullAddress: 'Видное, проспект Ленинского Комсомола, 1Д'
  phone: 84954093741
  yandex: f8274b102e2d7c34
- alias: vlasiha
  city: Власиха
  inCity: во Власихе
  coordinates:
    - 55.685503
    - 37.190423
  address: ''
  fullAddress: 'Московская область, посёлок Власиха'
  phone: 84954093741
  yandex: 63557712985a0c10
- alias: voskresenskoe
  city: Воскресенское
  inCity: в Воскресенском
  coordinates:
    - 55.517495
    - 37.442572
  address: ''
  fullAddress: 'Москва, поселение Воскресенское'
  phone: 84954093741
  yandex: d936dd177a893ce6
- alias: veshki
  city: Вёшки
  inCity: в Вёшках
  coordinates:
    - 55.928071
    - 37.608792
  address: 'Абрикосовая улица, 29'
  fullAddress: 'городской округ Мытищи, посёлок Вёшки, Абрикосовая улица, 29'
  phone: 84954093741
  yandex: 0eb127a91e39b2c6
- alias: dedovsk
  city: Дедовск
  inCity: в Дедовске
  coordinates:
    - 55.860787
    - 37.108605
  address: 'улица Набережная Речфлота, 1'
  fullAddress: 'городской округ Истра, Дедовск, улица Набережная Речфлота, 1'
  phone: 84954093741
  yandex: 94aeb6da31677c80
- alias: dzerzhinskii
  city: Дзержинский
  inCity: в Дзержинском
  coordinates:
    - 55.629155
    - 37.842798
  address: 'улица Стройгородок, вл5'
  fullAddress: 'Московская область, Дзержинский, улица Стройгородок, вл5'
  phone: 84954093741
  yandex: 1268fae8f8a876b0
- alias: dolgoprudnyi
  city: Долгопрудный
  inCity: в Долгопрудном
  coordinates:
    - 55.924219
    - 37.499902
  address: 'Промышленный проезд, 8'
  fullAddress: 'Долгопрудный, Промышленный проезд, 8'
  phone: 84954093741
  yandex: b215cb0d7fa2cb8a
- alias: domodedovo
  city: Домодево
  inCity: в Домодедово
  coordinates:
    - 55.33257
    - 37.843427
  address: 'улица Авенариуса, 5'
  fullAddress: 'Домодедово, микрорайон Белые Столбы, улица Авенариуса, 5'
  phone: 84954093741
  yandex: 9d6c05103a6eb952
- alias: zheleznodorozhnyi
  city: Железнодорожный
  inCity: в Железнодорожном
  coordinates:
    - 55.738556
    - 38.013613
  address: 'Автозаводская улица, 13Б'
  fullAddress: 'Балашиха, микрорайон Железнодорожный, Автозаводская улица, 13Б'
  phone: 84954093741
  yandex: 79fee4fe1995073d
- alias: zhukovskii
  city: Жуковский
  inCity: в Жуковском
  coordinates:
    - 55.61209
    - 38.107163
  address: 'улица Чапаева, 24'
  fullAddress: 'Жуковский, улица Чапаева, 24'
  phone: 84954093741
  yandex: 8becc8ae3ec6f4c5
- alias: zelenograd
  city: Зеленоград
  inCity: в Зеленограде
  coordinates:
    - 56.006603
    - 37.192382
  address: '2-й Западный проезд, 1с4'
  fullAddress: 'Зеленоград, 2-й Западный проезд, 1с4'
  phone: 84954093741
  yandex: 25badd0012883cae
- alias: ivanteevka
  city: Ивантеевка
  inCity: в Ивантеевке
  coordinates:
    - 55.960256
    - 37.930105
  address: 'улица Толмачёва, 104с1'
  fullAddress: 'Ивантеевка, улица Толмачёва, 104с1'
  phone: 84954093741
  yandex: dc2ae4d2b3cdafdf
- alias: ilinskoe
  city: Ильинское-Усово
  inCity: в Ильинское-Усово
  coordinates:
    - 55.766136
    - 37.220265
  address: ''
  fullAddress: 'городской округ Красногорск, посёлок Ильинское-Усово'
  phone: 84954093741
  yandex: 5cd156b9ffe3ec64
- alias: cliazma
  city: Клязьма
  inCity: в Клязьме
  coordinates:
    - 55.977743
    - 37.85197
  address: 'Костомаровская улица, 5/1с11'
  fullAddress: 'Пушкино, микрорайон Клязьма, Костомаровская улица, 5/1с11'
  phone: 84954093741
  yandex: afa6add859d548e1
- alias: korolev
  city: Королев
  inCity: в Королеве
  coordinates:
    - 55.910003
    - 37.799643
  address: 'Пионерская улица, 4к83'
  fullAddress: 'Королёв, Пионерская улица, 4к83'
  phone: 84954093741
  yandex: 3fedfea67e4288ca
- alias: kotelniki
  city: Котельники
  inCity: в Котельниках
  coordinates:
    - 55.665071
    - 37.862696
  address: 'Новая улица, 19с3'
  fullAddress: 'Котельники, Новая улица, 19с3'
  phone: 84954093741
  yandex: ef8bd46bc5d60c04
- alias: kraskovo
  city: Красково
  inCity: в Красково
  coordinates:
    - 55.663888
    - 37.993922
  address: 'улица Карла Маркса, 121с1'
  fullAddress: >-
    городской округ Люберцы, посёлок городского типа Красково, улица Карла
    Маркса, 121с1
  phone: 84954093741
  yandex: 8a10270707cdfba6
- alias: krasnogorsk
  city: Красногорск
  inCity: в Красногорске
  coordinates:
    - 55.8289
    - 37.343209
  address: 'Оптический проезд, 1'
  fullAddress: 'Красногорск, Оптический проезд, 1'
  phone: 84954093741
  yandex: 8c5cc48cb1a897f6
- alias: kurkino
  city: Куркино
  inCity: в Куркино
  coordinates:
    - 55.883191
    - 37.40822
  address: 'Куркинское шоссе, 13к1с1'
  fullAddress: 'Москва, Куркинское шоссе, 13к1с1'
  phone: 84954093741
  yandex: 7e5c16031370918a
- alias: lobnia
  city: Лобня
  inCity: в Лобне
  coordinates:
    - 56.01944
    - 37.462613
  address: 'улица Гагарина, 9с7'
  fullAddress: 'Лобня, улица Гагарина, 9с7'
  phone: 84954093741
  yandex: 7ed18d8cf571b331
- alias: lytkarino
  city: Лыткарино
  inCity: в Лыткарино
  coordinates:
    - 55.589762
    - 37.91424
  address: 'улица Степана Степанова, 9Е'
  fullAddress: 'Лыткарино, квартал 3А, улица Степана Степанова, 9Е'
  phone: 84954093741
  yandex: c73b7631a14e192c
- alias: lyubertcy
  city: Люберцы
  inCity: в Люберцах
  coordinates:
    - 55.664609
    - 37.887327
  address: 'Котельнический проезд, 25'
  fullAddress: 'Люберцы, Котельнический проезд, 25'
  phone: 84954093741
  yandex: b5a9f2fa4fe1ec1e
- alias: malahovka
  city: Малаховка
  inCity: в Малаховке
  coordinates:
    - 55.637083
    - 38.008124
  address: 'Шоссейная улица, 40с5'
  fullAddress: >-
    городской округ Люберцы, посёлок городского типа Малаховка, Шоссейная улица,
    40с5
  phone: 84954093741
  yandex: 0a8d939850b04ce2
- alias: moscow
  city: Москва
  inCity: в Москве
  coordinates:
    - 55.755814
    - 37.617635
  address: ''
  fullAddress: !<tag:yaml.org,2002:js/undefined> ''
  phone: 84954093741
  yandex: 2882d8a93f35322b
- alias: moskovskii
  city: Московский
  inCity: в Московском
  coordinates:
    - 55.593354
    - 37.371524
  address: 'Радужная улица, 3'
  fullAddress: 'Московский, микрорайон Град Московский, Радужная улица, 3'
  phone: 84954093741
  yandex: 94b70e3f40bd1d91
- alias: mytishchi
  city: Мытищи
  inCity: в Мытищах
  coordinates:
    - 55.923544
    - 37.715516
  address: 'улица Колпакова, 50с1'
  fullAddress: 'Мытищи, улица Колпакова, 50с1'
  phone: 84954093741
  yandex: 14c3722a9abe9fd5
- alias: nahabino
  city: Нахабино
  inCity: в Нахабино
  coordinates:
    - 55.841372
    - 37.177182
  address: 'Институтская улица, 17Ас1'
  fullAddress: >-
    городской округ Красногорск, рабочий посёлок Нахабино, Институтская улица,
    17Ас1
  phone: 84954093741
  yandex: da1b7e04f8ae4955
- alias: novogorsk
  city: Новогорск
  inCity: в Новогорске
  coordinates:
    - 55.905068
    - 37.340487
  address: 'Ивановская улица, 15Вс1'
  fullAddress: 'Химки, микрорайон Новогорск, Ивановская улица, 15Вс1'
  phone: 84954093741
  yandex: 49619a45dd2597f8
- alias: odintcovo
  city: Одинцово
  inCity: в Одинцово
  coordinates:
    - 55.671372
    - 37.249209
  address: 'Западная улица, 7'
  fullAddress: 'Одинцово, Западная улица, 7'
  phone: 84954093741
  yandex: 7e30f3c57b5e4385
- alias: opaliha
  city: Опалиха
  inCity: в Опалихе
  coordinates:
    - 55.825168
    - 37.265954
  address: 'улица Мира, 25'
  fullAddress: 'Красногорск, микрорайон Опалиха, улица Мира, 25'
  phone: 84954093741
  yandex: 2f4973a377beb836
- alias: petrovo-dalnee
  city: Петрово-Дальнее
  inCity: в Петрово-Дальнее
  coordinates:
    - 55.75974
    - 37.168055
  address: 'Промышленная улица, с1'
  fullAddress: 'городской округ Красногорск, село Петрово-Дальнее, Промышленная улица, с1'
  phone: 84954093741
  yandex: 9feace978aa44106
- alias: pirogovo
  city: Пирогово
  inCity: в Пирогово
  coordinates:
    - 55.974181
    - 37.734704
  address: 'Совхозная улица, 27/2'
  fullAddress: 'городской округ Мытищи, деревня Пирогово, Совхозная улица, 27/2'
  phone: 84954093741
  yandex: c5744df0ccd47aef
- alias: podolsk
  city: Подольск
  inCity: в Подольске
  coordinates:
    - 55.427428
    - 37.570429
  address: 'Рощинская улица, 3с2'
  fullAddress: 'Подольск, Рощинская улица, 3с2'
  phone: 84954093741
  yandex: 3a81c0bc0bc88339
- alias: putilkovo
  city: Путилково
  inCity: в Путилково
  coordinates:
    - 55.867874
    - 37.387604
  address: 'Путилковское шоссе, 28'
  fullAddress: 'городской округ Красногорск, деревня Путилково, Путилковское шоссе, 28'
  phone: 84954093741
  yandex: c389d10ce50ccb85
- alias: pushkino
  city: Пушкино
  inCity: в Пушкине
  coordinates:
    - 55.990891
    - 37.853811
  address: 'Кудринское шоссе, 6с6'
  fullAddress: 'Московская область, Пушкино, Кудринское шоссе, 6с6'
  phone: 84954093741
  yandex: 12877f19048be05a
- alias: rastorguevo
  city: Расторгуево
  inCity: в Расторгуево
  coordinates:
    - 55.53859
    - 37.669432
  address: 'Сосновая улица, 15к1'
  fullAddress: 'Видное, район Расторгуево, Сосновая улица, 15к1'
  phone: 84954093741
  yandex: 17e9bb6208af8824
- alias: reutov
  city: Реутов
  inCity: в Реутове
  coordinates:
    - 55.759881
    - 37.875649
  address: 'улица Гагарина, 33/2Б'
  fullAddress: 'Реутов, улица Гагарина, 33/2Б'
  phone: 84954093741
  yandex: 1ac525cf216ea481
- alias: rublevo
  city: Рублево
  inCity: в Рублево
  coordinates:
    - 55.793019
    - 37.353674
  address: 'улица Василия Ботылёва, 52с248'
  fullAddress: 'посёлок Рублёво, улица Василия Ботылёва, 52с248'
  phone: 84954093741
  yandex: 5ac9fe07c7ad2fb1
- alias: saltykovka
  city: Салтыковка
  inCity: в Салтыковке
  coordinates:
    - 55.752485
    - 37.939313
  address: 'Носовихинское шоссе, вл255'
  fullAddress: 'Балашиха, микрорайон Салтыковка, Носовихинское шоссе, вл255'
  phone: 84954093741
  yandex: c027362d0e481fa9
- alias: shodnya
  city: Сходня
  inCity: в Сходне
  coordinates:
    - 55.948977
    - 37.306854
  address: 'Железнодорожная улица, 8'
  fullAddress: 'Химки, микрорайон Сходня, Железнодорожная улица, 8'
  phone: 84954093741
  yandex: ef8f844f56c5cb83
- alias: tomilino
  city: Томилино
  inCity: в Томилино
  coordinates:
    - 55.663167
    - 37.963172
  address: 'улица Гаршина, 11с7'
  fullAddress: >-
    городской округ Люберцы, посёлок городского типа Томилино, улица Гаршина,
    11с7
  phone: 84954093741
  yandex: ae657c223c8012cf
- alias: troitck
  city: Троицк
  inCity: в Троицке
  coordinates:
    - 55.454902
    - 37.274757
  address: 'Физическая улица, 27с35'
  fullAddress: 'Троицк, Физическая улица, 27с35'
  phone: 84954093741
  yandex: ffe5becdfb7e1366
- alias: himki
  city: Химки
  inCity: в Химках
  coordinates:
    - 55.886292
    - 37.432654
  address: 'улица Горшина, 3к2'
  fullAddress: 'Химки, улица Горшина, 3к2'
  phone: 84954093741
  yandex: 8cbe21192e0cf796
- alias: shchelkovo
  city: Щелково
  inCity: в Щелково
  coordinates:
    - 55.913818
    - 38.035478
  address: 'Заводская улица, 2к88'
  fullAddress: 'Щёлково, Заводская улица, 2к88'
  phone: 84954093741
  yandex: 86b36d35b4d7ca20
- alias: shcherbinka
  city: Щербинка
  inCity: в Щербинке
  coordinates:
    - 55.492156
    - 37.560484
  address: 'Южная улица, 14'
  fullAddress: 'Щербинка, Южная улица, 14'
  phone: 84954093741
  yandex: 3fb91ed8cae84553
